# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evennia_wiki', '0002_add_title_to_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='can_read',
            field=models.CharField(default='Developer', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='can_write',
            field=models.CharField(default='Developer', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='address',
            field=models.CharField(db_index=True, max_length=2000, unique=True),
        ),
    ]
